title: Marc Saribay # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  IT professional with over 15 years of work experience as a Programmer Analyst and Software Engineer. 
  <br><br>
  Performs design and development work on complex software development projects and offers technical solutions on application issues. Competent in programming on several programming languages across different platforms.
  <br><br>
  <a href="https://www.linkedin.com/in/marc-saribay-40057717b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
